name: "Release"
on:
  push:
    branches: [main]

jobs:
  build:
    environment: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Build & test
        run: |
          npm run setup
          npx lerna run test
      - name: Setup Git
        run: |
          git config --global user.email action@github.com
          git config --global user.name GitHub Action
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx lerna publish --yes
